### PR TITLE
Updates for PureScript 0.11

### PR DESCRIPTION
**Pull request by simonyangme**
Needed for https://github.com/owickstrom/purescript-spec/pull/45

Waiting on https://github.com/Thimoteus/purescript-mmorph/pull/4 to be merged and published

### CODE REVIEW

**Comment by justinwoo** [comment]
Looks like upstream mmorph is live now: https://github.com/Thimoteus/purescript-mmorph/releases

**Comment by simonyangme** [comment]
Yup. Just pushed changes. There are breaking changes due to split of `MonadThrow` from `MonadError`

**Comment by simonyangme** [comment]
@felixSchl please cut a release when you can. Thanks for taking the PR!

**Comment by felixSchl** [comment]
@simonyangme  [v4.0.0](https://github.com/felixSchl/purescript-pipes/releases/tag/v4.0.0)

**Pull request merged**
